### PR TITLE
Replace Manual SQL with Android SQL Room

### PR DESCRIPTION
**Pull request by Mithrandir21**
- Debug variant for testing and building purposes.
- Added Compile option set to Java 8.
- Added Room Dependencies.
- Added Kapt plugin for annotation processing.
- Replaced manual SQL queries with compiled SQL with Room.

### CODE REVIEW

**Comment by alirezat775** [comment]
thanks for contributing in downloader, some issue is important for pull request:
please create a feature branch from development and send a pull request to merge development.
explain better in a commit message, comment very good if showing in project commits.
please don't remove class author and add your data in a header of class
and the last question why replace room with sqlite?

**Comment by alirezat775** [comment]
@Mithrandir21, please answer previously comment

**Comment by Mithrandir21** [comment]
Hello. Apologies for the delayed answer.
Thank you for the looking at the possible change.
The reasons I thought that replacing SQLite with Room would be better are as following:

1. Room is backed by SQLite
2. Room allows you skip a lot boilerplate code and issues with manual table creation.
3. SQL queries against Room can be stated in simple SQL, instead of joining separate strings together.
4. SQL queries against Room at all checked at compile time, so you spot errors when writing the code instead of when running the code.

There are a bunch of there benefits as well, but those might only apply to larger data relationships.
There is a lot of info out there about the benefits of Room over SQLite, which I am sure you are aware of.


About creating a 'feature branch', I don't write access to this Repo, so I am not allowed to create a Feature branch. I therefore had to create a Fork and create a PR from there into your Dev branch.

I will add the Class authors back.

**Comment by alirezat775** [comment]
Hi @Mithrandir21, thanks for the reply, I have one concern for using room, is conflict owner app module with downloader library if using api instead of implementation in gradle  that fixed

about your access in a feature branch, that's true you don't  have access write to a repo, you should 
be committed a change in a development branch and create PR.
could you please add your change in a development branch and create PR for a merge to development branch?

thanks for contributing

**Comment by Mithrandir21** [comment]
Thank you for opening the PR again.
I have created a new PR from a specific Feature branch in my own Repo to keep things clean.

I am unaware of the issue with using API instead of the implementation.
However, the downloader SQL db will only be in the file you have specified, 'downloader_db', so there really should not be any need to open the SQLite directly as all queries that can be produced manually, can also be produced via Room.

Additionally, it is much easier to setup additional functionality from the Room implementation, such as returning Rx observables.

**Comment by alirezat775** [comment]
This close because merged in another PR [https://github.com/alirezat775/downloader/pull/3](url)

**Pull request closed without merging**
